const API=location.port==='5173'?'http://localhost:8000':'';
const app=document.querySelector('#app');
const state={page:'dashboard',stats:null,sections:[],sources:[],mode:'smart',length:20,filters:{source:'',area:'',section:'',state:'all'},session:null,question:null,feedback:null,summary:null,error:'',busy:false,search:'',offset:0,terms:{items:[],total:0},detail:null};
const labels={new:'Neu',learning:'Im Aufbau',review:'Wiederholung',mastered:'Gemeistert'};
const modes={smart:['Smart Learning','Fälliges, Schwächen und neue Begriffe im richtigen Mix.'],random:['Freies Training','Zufällig üben. Ohne Änderung des Lernplans.'],weak:['Schwache Begriffe','Unsicheres Wissen gezielt festigen.'],due:['Fällige Reviews','Wiederholen, wenn es langfristig zählt.'],new:['Neue Begriffe','Den nächsten Teil des Lernstoffs entdecken.']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(c,n)=>n?`${Math.round(c/n*100)} %`:'–';
const date=v=>v?new Date(v).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'}):'Noch nicht';
async function api(path,data){const r=await fetch(API+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error||'Anfrage fehlgeschlagen');return result;}
async function refresh(){const [s,c]=await Promise.all([api('/api/stats'),api('/api/sections')]);state.stats=s;state.sections=c.sections;state.sources=c.sources;}
async function run(fn){if(state.busy)return;state.busy=true;state.error='';render();try{await fn();}catch(e){state.error=e.message;}finally{state.busy=false;render();}}
function filterUI(){const select=(key,title,options)=>`<label>${title}<select data-filter="${key}">${options.map(([value,label])=>`<option value="${esc(value)}" ${state.filters[key]===value?'selected':''}>${esc(label)}</option>`).join('')}</select></label>`;return `<div class="filters">${select('source','Quelldatei',[['','Alle Quellen'],...state.sources.map(s=>[s.id,s.title])])}${select('area','Fachgebiet',[['','Alle Gebiete'],...[...new Set(state.sections.filter(s=>!state.filters.source||s.source_id===state.filters.source).map(s=>s.area))].sort().map(a=>[a,a])])}${select('section','Abschnitt',[['','Alle Abschnitte'],...state.sections.filter(s=>(!state.filters.area||s.area===state.filters.area)&&(!state.filters.source||s.source_id===state.filters.source)).map(s=>[s.id,`${s.code} · ${s.title}`])])}${select('state','Lernstatus',[['all','Alle Begriffe'],['weak','Nur schwache'],['new','Nur neue'],['due','Nur fällige'],['mastered','Nur gemeisterte']])}</div>`;}
function metric(label,value,sub=''){return `<div class="metric"><span>${label}</span><strong>${value}</strong><small>${sub}</small></div>`;}
function dashboard(){const s=state.stats;return `<div class="heading"><div><p class="eyebrow">DEIN LERNÜBERBLICK</p><h1>Wissen, das bleibt.</h1><p>Schritt für Schritt sicher durch deine IT-Fachbegriffe.</p></div><span class="pill">● Lokal gespeichert · SQLite</span></div>
 <div class="hero"><div><p class="eyebrow">LANGFRISTIG GEMEISTERT</p><h2>${s.mastered.toLocaleString('de-DE')} <span>/ ${s.total.toLocaleString('de-DE')}</span></h2><p>Fachbegriffe mit nachgewiesenem Wissen in beiden Richtungen.</p><progress max="100" value="${s.percentage}"></progress><div class="hero-bottom"><span>${s.percentage.toFixed(1)} % gemeistert</span><span>${s.learning} im Aufbau · ${s.new} neu</span></div></div><div class="review-callout"><span class="review-number">${s.due}</span><span>Reviews warten auf dich</span><button data-action="due" class="light">Jetzt wiederholen ↗</button></div></div>
 <div class="metrics">${metric('Antwortgenauigkeit',s.accuracy.toFixed(1)+' %','Alle Antworten inkl. freiem Training')}${metric('Fragen beantwortet',s.answered,`${s.correct} richtig · ${s.wrong} falsch`)}${metric('Aktuelle Serie',s.streak,'Richtige Antworten in Folge')}${metric('Beste Serie',s.bestStreak,'Dein bisheriger Rekord')}</div>
 <section class="panel"><div class="section-heading"><div><p class="eyebrow">DEINE NÄCHSTE EINHEIT</p><h2>Wie möchtest du lernen?</h2></div><span class="muted">Qualität vor Tempo.</span></div><div class="mode-grid">${Object.entries(modes).map(([k,[title,desc]],i)=>`<button class="mode ${state.mode===k?'active':''}" data-mode="${k}"><span class="mode-icon">${['✦','⤨','◎','◷','＋'][i]}</span><strong>${title}</strong><small>${desc}</small></button>`).join('')}</div>${filterUI()}<div class="start-row"><label>Umfang<select id="length">${[10,20,50,100,0].map(n=>`<option value="${n}" ${state.length===n?'selected':''}>${n?n+' Fragen':'Endlos'}</option>`).join('')}</select></label><p>Jede Frage: 6 Antworten. Beide Lernrichtungen.<br><small>Frühes Üben zählt nicht als zeitversetzter Review.</small></p><button class="primary" data-action="start">Lerneinheit starten →</button></div></section>
 <div class="note"><strong>Wann gilt ein Begriff als gemeistert?</strong><p>Mindestens 5 richtige Antworten, 80 % Genauigkeit, je 2 richtige Antworten pro Richtung und 3 fällige Reviews über wachsende Zeitabstände. Die letzten 5 Antworten müssen richtig sein.</p></div>`;}
function quiz(){const q=state.question,s=state.session,f=state.feedback;if(!q)return '<div class="panel">Frage wird geladen … <button data-action="next">Erneut laden</button></div>';return `<div class="heading"><div><p class="eyebrow">${esc(modes[s.mode][0])}</p><h1>Ein Begriff. Ein Schritt weiter.</h1></div><button class="secondary" data-action="stop">Sitzung beenden</button></div><div class="quiz-stats"><span>Frage ${q.number}${s.length?' / '+s.length:' · Endlos'}</span><span>${pct(s.correct_answers,s.questions_answered)} Sitzungsgenauigkeit</span><span>${state.stats.mastered} gemeistert · ${state.stats.learning} im Aufbau · ${state.stats.new} neu</span></div>${s.length?`<progress value="${s.questions_answered}" max="${s.length}"></progress>`:''}<section class="question panel"><div class="question-label"><span class="pill">${q.direction==='a'?'Begriff → Bedeutung':'Bedeutung → Begriff'}</span><span class="muted">Genau eine Antwort ist richtig</span></div><p class="question-hint">${q.direction==='a'?'Was bedeutet dieser Fachbegriff?':'Welcher Fachbegriff passt zu dieser Bedeutung?'}</p><h2>${esc(q.prompt)}</h2><div class="answers">${q.choices.map((c,i)=>`<button class="answer ${f?(c.token===f.correctToken?'correct':c.token===f.selected?'incorrect':'dim'):''}" data-choice="${c.token}" ${f||state.busy?'disabled':''}><span class="choice-index">${i+1}</span><span>${esc(c.text)}</span>${f&&c.token===f.correctToken?'<b>✓</b>':''}${f&&!f.correct&&c.token===f.selected?'<b>×</b>':''}</button>`).join('')}</div>${f?`<div class="feedback ${f.correct?'success':'failure'}" role="status"><strong>${f.correct?'Richtig. Gut erinnert!':'Noch nicht ganz. Das ist das richtige Paar:'}</strong><h3>${esc(f.fachbegriff)}</h3><p>${esc(f.bedeutung)}</p><small>${f.practiceOnly?'Freies Training: Lernplan unverändert.':`${labels[f.progress.status]} · ${f.progress.mastery_score} / 100 · Nächster Review: ${date(f.progress.next_review_at)}`}</small></div><div class="next-row"><button class="primary" data-action="next">${s.length&&s.questions_answered>=s.length?'Auswertung ansehen':'Nächste Frage'} →</button></div>`:'<p class="keyboard-hint">Tastatur: 1–6 zum Antworten</p>'}</section>`;}
function summary(){const s=state.summary;const list=terms=>terms.length?terms.map(t=>`<li><span>${esc(t.fachbegriff)}</span><b>${t.mastery_score} %</b></li>`).join(''):'<li>Noch keine Antworten.</li>';return `<div class="heading"><div><p class="eyebrow">EINHEIT ABGESCHLOSSEN</p><h1>Ein guter Schritt nach vorn.</h1><p>${esc(state.endReason||'Deine Antworten wurden dauerhaft gespeichert.')}</p></div><button class="primary" data-page="dashboard">Zur Lernübersicht →</button></div><div class="metrics">${metric('Fragen',s.questions_answered)}${metric('Richtig',s.correct_answers)}${metric('Falsch',s.wrong_answers)}${metric('Genauigkeit',s.accuracy.toFixed(1)+' %')}</div><div class="summary-banner"><strong>+${s.newlyMastered} neu gemeistert</strong><span>${s.lostMastery} Begriffe haben ihren Meisterstatus verloren</span></div><div class="two-columns"><section class="panel"><h2>Weiter festigen</h2><p>Begriffe mit dem niedrigsten Meisterschaftswert</p><ul class="term-list">${list(s.weakest)}</ul></section><section class="panel"><h2>Deine stärksten Begriffe</h2><p>Nach langfristigem Meisterschaftswert</p><ul class="term-list">${list(s.strongest)}</ul></section></div>${s.mode==='random'?'<div class="note">Freies Training wurde in der Antwortstatistik gespeichert. Meisterschaft und Review-Zeitpunkte bleiben unverändert.</div>':''}`;}
function library(){return `<div class="heading"><div><p class="eyebrow">DEIN WISSENSARCHIV</p><h1>Jeder Begriff zählt.</h1><p>Originaltexte, Lernstand und beide Lernrichtungen im Detail.</p></div></div><section class="panel">${filterUI()}<form id="search-form"><input id="search" type="search" placeholder="Begriff oder Bedeutung suchen …" value="${esc(state.search)}" aria-label="Begriff suchen"><button class="secondary">Suchen</button></form><div class="table-wrap"><table><thead><tr><th>Fachbegriff</th><th>Status</th><th>Meisterschaft</th><th>Genauigkeit</th><th>Antworten</th><th>Nächster Review</th></tr></thead><tbody>${state.terms.items.map(t=>`<tr><td><button class="text-button" data-term="${t.id}">${esc(t.fachbegriff)}</button></td><td><span class="badge ${t.status}">${labels[t.status]}</span></td><td>${t.mastery_score} %</td><td>${pct(t.correct_count,t.times_seen)}</td><td>${t.times_seen}</td><td>${date(t.next_review_at)}</td></tr>`).join('')||'<tr><td colspan="6">Keine passenden Begriffe.</td></tr>'}</tbody></table></div><div class="pagination"><button class="secondary" data-action="prev" ${state.offset===0?'disabled':''}>← Zurück</button><span>${state.terms.total?state.offset+1:0}–${Math.min(state.offset+50,state.terms.total)} von ${state.terms.total}</span><button class="secondary" data-action="more" ${state.offset+50>=state.terms.total?'disabled':''}>Weiter →</button></div></section>`;}
function sections(){return `<div class="heading"><div><p class="eyebrow">FACHGEBIETE IM VERGLEICH</p><h1>Wo stehst du?</h1><p>Meisterschaft misst langfristige Sicherheit. Genauigkeit misst bisherige Antworten im Lernplan.</p></div></div><div class="section-grid">${state.sections.map(s=>`<button class="panel section-card" data-section="${s.id}"><span class="eyebrow">${esc(s.code)}</span><h3>${esc(s.title)}</h3><div class="section-score"><strong>${pct(s.mastered,s.total)}</strong><span>gemeistert</span></div><progress max="${s.total}" value="${s.mastered}"></progress><small>${s.mastered} / ${s.total} Begriffe · ${pct(s.correct,s.answered)} Genauigkeit</small></button>`).join('')}</div>`;}
function detail(){const t=state.detail;return `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="detail-title" tabindex="-1"><button class="close secondary" data-action="close" aria-label="Schließen">×</button><p class="eyebrow">BEGRIFF IM DETAIL</p><h2 id="detail-title">${esc(t.fachbegriff)}</h2><p class="definition">${esc(t.bedeutung)}</p><span class="badge ${t.status}">${labels[t.status]}</span><div class="metrics compact">${metric('Meisterschaft',t.mastery_score+' %')}${metric('Genauigkeit',pct(t.correct_count,t.times_seen))}${metric('Antworten',t.times_seen,`${t.correct_count} richtig · ${t.wrong_count} falsch`)}${metric('Richtige Serie',t.correct_streak)}</div><dl><dt>Fragen angezeigt (alle Modi)</dt><dd>${t.times_shown}</dd><dt>Begriff → Bedeutung</dt><dd>${pct(t.correct_a,t.correct_a+t.wrong_a)} · ${t.correct_a} richtig / ${t.wrong_a} falsch</dd><dt>Bedeutung → Begriff</dt><dd>${pct(t.correct_b,t.correct_b+t.wrong_b)} · ${t.correct_b} richtig / ${t.wrong_b} falsch</dd><dt>Fällige Reviews</dt><dd>${t.successful_reviews} bestanden / ${t.failed_reviews} fehlgeschlagen</dd><dt>Zuletzt gelernt</dt><dd>${date(t.last_reviewed_at)}</dd><dt>Nächster Review</dt><dd>${date(t.next_review_at)}</dd></dl><small>Freies Training wird nur im Verlauf und in der Gesamtstatistik gezählt.</small><h3>Letzte Antworten</h3><ul class="term-list">${t.history.map(h=>`<li><span>${h.was_correct?'✓ Richtig':'× Falsch'} · ${h.direction==='a'?'Begriff → Bedeutung':'Bedeutung → Begriff'}</span><small>${date(h.answered_at)}</small></li>`).join('')||'<li>Noch nicht beantwortet.</li>'}</ul></section></div>`;}
function render(){app.innerHTML=`<aside><a class="brand" href="/">b<span>Begriffwerk<small>DEIN IT-LERNSTUDIO</small></span></a><nav>${[['dashboard','◫','Lernübersicht'],['library','▤','Begriffe'],['sections','▥','Fachgebiete']].map(([page,icon,title])=>`<button data-page="${page}" class="${state.page===page?'selected':''}"><span>${icon}</span>${title}</button>`).join('')}${state.session&&!state.summary?'<button data-page="quiz">▷ Laufende Einheit</button>':''}</nav><div class="sidebar-bottom"><span class="status-dot"></span> Dein Wissen. Dein Tempo.<p>Originaldaten. Echte Fortschritte.<br>Alles bleibt auf deinem Gerät.</p></div></aside><main>${state.error?`<div role="alert" class="error">${esc(state.error)} <button data-action="retry">Erneut versuchen</button></div>`:''}${!state.stats?'<div class="panel">Lernstudio wird geladen …</div>':state.page==='dashboard'?dashboard():state.page==='quiz'?quiz():state.page==='summary'?summary():state.page==='library'?library():sections()}<footer>BEGRIFFWERK <span>Langfristiges Lernen statt schneller Häkchen.</span></footer></main>${state.detail?detail():''}${state.busy?'<div class="loading" role="status">Wird gespeichert / geladen …</div>':''}`;
 bind();}
async function loadTerms(){state.terms=await api('/api/progress?'+new URLSearchParams({...state.filters,search:state.search,offset:state.offset}));}
async function next(){state.question=await api('/api/quiz/next?sessionId='+state.session.id);state.feedback=null;if(state.question.done){state.summary=state.question.summary;state.endReason=state.question.reason;state.page='summary';localStorage.removeItem('begriffwerk-session');await refresh();}else state.page='quiz';}
function bind(){
 app.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>run(async()=>{state.page=el.dataset.page;if(state.page==='library')await loadTerms();else if(state.page==='dashboard'||state.page==='sections')await refresh();}));
 app.querySelectorAll('[data-mode]').forEach(el=>el.onclick=()=>{state.mode=el.dataset.mode;render();});
 app.querySelectorAll('[data-filter]').forEach(el=>el.onchange=()=>run(async()=>{state.filters[el.dataset.filter]=el.value;if(el.dataset.filter==='source'){state.filters.area='';state.filters.section='';}if(el.dataset.filter==='area')state.filters.section='';state.offset=0;if(state.page==='library')await loadTerms();}));
 app.querySelector('#length')?.addEventListener('change',e=>state.length=Number(e.target.value));
 app.querySelector('#search-form')?.addEventListener('submit',e=>{e.preventDefault();state.search=app.querySelector('#search').value;state.offset=0;run(loadTerms);});
 app.querySelectorAll('[data-choice]').forEach(el=>el.onclick=()=>run(async()=>{const f=await api('/api/quiz/answer',{sessionId:state.session.id,questionId:state.question.id,choiceToken:el.dataset.choice});state.feedback={...f,selected:el.dataset.choice};state.session=f.session;state.stats=await api('/api/stats');}));
 app.querySelectorAll('[data-term]').forEach(el=>el.onclick=()=>run(async()=>{state.detail=await api('/api/terms/'+el.dataset.term);}));
 app.querySelectorAll('[data-section]').forEach(el=>el.onclick=()=>{state.filters={source:'',area:'',section:el.dataset.section,state:'all'};state.page='dashboard';render();});
 app.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>run(async()=>{switch(el.dataset.action){
  case 'start': if(state.session&&!state.summary)await api('/api/quiz/stop',{sessionId:state.session.id});state.session=await api('/api/quiz/session',{mode:state.mode,length:state.length,filters:state.filters});state.summary=null;state.endReason='';localStorage.setItem('begriffwerk-session',state.session.id);await next();break;
  case 'due':state.mode='due';document.querySelector('.mode-grid')?.scrollIntoView({behavior:'smooth'});break;
  case 'next':await next();break;
  case 'stop':state.summary=await api('/api/quiz/stop',{sessionId:state.session.id});state.page='summary';localStorage.removeItem('begriffwerk-session');await refresh();break;
  case 'more':state.offset+=50;await loadTerms();break;
  case 'prev':state.offset=Math.max(0,state.offset-50);await loadTerms();break;
  case 'close':state.detail=null;break;
  case 'retry':await refresh();if(state.page==='library')await loadTerms();if(state.page==='quiz'&&!state.feedback)await next();break;
 }}));
}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.detail){state.detail=null;render();return;}if(state.detail&&e.key==='Tab'){const buttons=[...document.querySelectorAll('.modal button')];if(buttons.length===1){e.preventDefault();buttons[0].focus();}return;}if(state.page==='quiz'&&!state.feedback&&!state.busy&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&/^[1-6]$/.test(e.key))app.querySelectorAll('[data-choice]')[Number(e.key)-1]?.click();});
await run(async()=>{await refresh();const saved=localStorage.getItem('begriffwerk-session');if(saved){try{state.session=await api('/api/quiz/session?id='+saved);if(!state.session.finished_at)await next();else{state.session=null;localStorage.removeItem('begriffwerk-session');}}catch{localStorage.removeItem('begriffwerk-session');state.session=null;}}});
