import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,writeFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { database } from '../backend/db.js';
import { importFiles } from '../backend/import.js';
import { makeChoices,updateProgress,weight,weightedPick } from '../backend/learning.js';
import { Service } from '../backend/service.js';
function fixture(){const db=database(':memory:');importFiles(db);return {db,service:new Service(db)};}
function fresh(){const {db}=fixture();const p=db.prepare('SELECT * FROM progress LIMIT 1').get();db.close();return p;}
function master(){let p=fresh(),now=100000;for(const direction of ['a','b','a','b','a']){now=p.next_review_at??now;p=updateProgress(p,true,direction,now);}return p;}
test('import is idempotent and all source pairs retain exact wording',()=>{const {db,service}=fixture();const before=service.catalog.length;const report=importFiles(db);assert.equal(report.uniqueTerms,before);assert.equal(report.files,13);assert.equal(db.prepare('SELECT count(*) n FROM progress').get().n,before);assert.ok(before>1000);db.close();});
test('same pair across sections shares progress; import validation rolls back',()=>{const dir=mkdtempSync(join(tmpdir(),'terms-'));const db=database(':memory:');try{const doc={titel:'T',thema:'X',bereiche:[{id:'A-01',titel:'X',fachbegriffe:[{fachbegriff:' Genau ',bedeutung:' Original. '}]},{id:'A-02',titel:'Y',fachbegriffe:[{fachbegriff:' Genau ',bedeutung:' Original. '}]}]};writeFileSync(join(dir,'terms.json'),JSON.stringify(doc));importFiles(db,dir);assert.equal(db.prepare('SELECT count(*) n FROM terms').get().n,1);assert.equal(db.prepare('SELECT count(*) n FROM term_sections').get().n,2);assert.equal(db.prepare('SELECT fachbegriff FROM terms').get().fachbegriff,' Genau ');doc.bereiche[0].fachbegriffe.push({fachbegriff:'bad'});writeFileSync(join(dir,'terms.json'),JSON.stringify(doc));assert.throws(()=>importFiles(db,dir));assert.equal(db.prepare('SELECT count(*) n FROM terms').get().n,1);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
test('all supplied terms support six unique choices and exactly one correct in both directions',()=>{const {db,service}=fixture();for(const term of service.catalog)for(const direction of ['a','b']){const choices=makeChoices(term,service.catalog,direction);assert.equal(choices.length,6);assert.equal(new Set(choices.map(c=>c.text)).size,6);assert.equal(choices.filter(c=>c.correct).length,1);assert.equal(choices.find(c=>c.correct).text,term[direction==='a'?'bedeutung':'fachbegriff']);}db.close();});
test('answer position randomized',()=>{const {db,service}=fixture(),positions=new Set();for(let i=0;i<100;i++)positions.add(makeChoices(service.catalog[0],service.catalog,'a').findIndex(c=>c.correct));assert.equal(positions.size,6);db.close();});
test('exact matching ambiguity and normalized duplicate options are excluded',()=>{const all=Array.from({length:10},(_,i)=>({id:String(i),fachbegriff:'Term '+i,bedeutung:'Definition '+i,section_ids:['s'],areas:['A']}));all.push({...all[0],id:'alias',fachbegriff:'Alias'});for(const d of ['a','b']){const c=makeChoices(all[0],all,d);assert.equal(c.length,6);assert.ok(!c.some(x=>x.text==='Alias'));}assert.throws(()=>makeChoices(all[0],all.slice(0,3),'a'));});
test('correct raises mastery; incorrect lowers it and schedules sooner',()=>{let p=updateProgress(fresh(),true,'a',1000);assert.ok(p.mastery_score>0);const before=p.mastery_score;p=updateProgress(p,false,'b',2000);assert.ok(p.mastery_score<before);assert.equal(p.next_review_at,122000);assert.equal(p.correct_a,1);assert.equal(p.wrong_b,1);assert.equal(p.correct_b,0);});
test('one success and massed repetition never master a term',()=>{let p=fresh();for(let i=0;i<100;i++)p=updateProgress(p,true,i%2?'a':'b',1000+i);assert.notEqual(p.status,'mastered');assert.equal(p.successful_reviews,0);assert.equal(p.stage,0);});
test('mastery needs both directions and elapsed increasing intervals',()=>{const p=master();assert.equal(p.status,'mastered');assert.ok(p.successful_reviews>=3);let single=fresh();for(let i=0;i<8;i++)single=updateProgress(single,true,'a',single.next_review_at??1000);assert.notEqual(single.status,'mastered');});
test('repeated wrong answers revoke mastery and lower review interval',()=>{let p=master();const previous=p.mastery_score;p=updateProgress(p,false,'b',p.next_review_at);p=updateProgress(p,false,'a',p.next_review_at);assert.equal(p.status,'review');assert.ok(p.mastery_score<previous);assert.equal(p.failed_reviews,2);assert.equal(p.correct_streak,0);});
test('overdue terms outrank new and not-due mastered terms',()=>{const p=fresh();assert.ok(weight({...p,next_review_at:0},1000)>weight(p,1000));assert.ok(weight(p,1000)>weight({...p,status:'mastered',next_review_at:100000},1000));});
test('server randomizes directions, hides answer and rejects duplicates; cooldown spans sessions',()=>{const {db,service}=fixture();const s=service.start({length:100});const directions=new Set(),recent=[];for(let i=0;i<100;i++){const q=service.next(s.id);directions.add(q.direction);assert.equal(q.choices.length,6);assert.equal(q.correctToken,undefined);assert.ok(q.choices.every(c=>!('correct' in c)));assert.deepEqual(service.next(s.id),q);const privateQ=db.prepare('SELECT * FROM questions WHERE id=?').get(q.id);assert.ok(!recent.slice(-3).includes(privateQ.term_id));recent.push(privateQ.term_id);service.answer({sessionId:s.id,questionId:q.id,choiceToken:privateQ.correct_token});assert.throws(()=>service.answer({sessionId:s.id,questionId:q.id,choiceToken:privateQ.correct_token}));}assert.equal(directions.size,2);assert.equal(service.next(s.id).done,true);assert.equal(service.stats().answered,100);assert.equal(service.stats().mastered,0);db.close();});
test('random practice persists history without changing progress',()=>{const {db,service}=fixture();const s=service.start({mode:'random',length:10}),q=service.next(s.id);const privateQ=db.prepare('SELECT * FROM questions WHERE id=?').get(q.id);const before=db.prepare('SELECT * FROM progress WHERE term_id=?').get(privateQ.term_id);service.answer({sessionId:s.id,questionId:q.id,choiceToken:privateQ.correct_token});assert.deepEqual(db.prepare('SELECT * FROM progress WHERE term_id=?').get(privateQ.term_id),before);assert.equal(service.stats().answered,1);db.close();});
test('invalid tokens and wrong sessions do not mutate progress; stop closes session',()=>{const {db,service}=fixture();const s=service.start(),other=service.start(),q=service.next(s.id);assert.throws(()=>service.answer({sessionId:s.id,questionId:q.id,choiceToken:'invalid'}));assert.throws(()=>service.answer({sessionId:other.id,questionId:q.id,choiceToken:q.choices[0].token}));assert.equal(service.stats().answered,0);assert.equal(service.finish(s.id).questions_answered,0);assert.equal(service.next(s.id).done,true);db.close();});
test('filters and due/new modes work; no matches yields a clear error',()=>{const {db,service}=fixture();assert.throws(()=>service.start({mode:'due'}),/Keine passenden/);const section=service.sections()[0];const s=service.start({filters:{section:section.id},mode:'new'});const q=service.next(s.id);const t=db.prepare('SELECT term_id FROM questions WHERE id=?').get(q.id);assert.ok(service.catalog.find(x=>x.id===t.term_id).section_ids.includes(section.id));assert.equal(service.terms({area:'ZZ'}).length,0);db.close();});
test('priority bands do not dilute one overdue term among a thousand new terms',()=>{const p=fresh();const due={...p,id:'due',next_review_at:0};const many=[due,...Array.from({length:1000},(_,i)=>({...p,id:String(i)}))];assert.equal(weightedPick(many,()=>.5,1000).id,'due');});
test('mistakes reappear within seven intervening questions, never immediately',()=>{const {db,service}=fixture();const session=service.start({length:20});let mistaken,returned=false;for(let i=0;i<9;i++){const q=service.next(session.id);const stored=db.prepare('SELECT * FROM questions WHERE id=?').get(q.id);if(i===0)mistaken=stored.term_id;else if(stored.term_id===mistaken){assert.ok(i>=4&&i<=7);returned=true;break;}const choice=i===0?q.choices.find(c=>c.token!==stored.correct_token).token:stored.correct_token;service.answer({sessionId:session.id,questionId:q.id,choiceToken:choice});}assert.ok(returned);db.close();});
test('database reopen preserves question, answer, schedule, and session',()=>{const dir=mkdtempSync(join(tmpdir(),'learning-db-')),path=join(dir,'test.sqlite');let db=database(path);try{importFiles(db);let svc=new Service(db);const s=svc.start(),q=svc.next(s.id),stored=db.prepare('SELECT * FROM questions WHERE id=?').get(q.id);svc.answer({sessionId:s.id,questionId:q.id,choiceToken:stored.correct_token});db.close();db=database(path);svc=new Service(db);assert.equal(svc.stats().answered,1);assert.equal(svc.session(s.id).questions_answered,1);assert.ok(svc.detail(stored.term_id).next_review_at);assert.equal(svc.detail(stored.term_id).history.length,1);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
test('session summary contains practiced strongest/weakest terms and real mastery changes',()=>{const {db,service}=fixture();const s=service.start();const q=service.next(s.id),stored=db.prepare('SELECT * FROM questions WHERE id=?').get(q.id);service.answer({sessionId:s.id,questionId:q.id,choiceToken:stored.correct_token});let summary=service.summary(s.id);assert.equal(summary.weakest.length,1);assert.equal(summary.strongest[0].id,stored.term_id);assert.equal(summary.newlyMastered,0);db.prepare("UPDATE progress SET status='mastered' WHERE term_id=?").run(stored.term_id);assert.equal(service.summary(s.id).newlyMastered,1);db.prepare('UPDATE quiz_sessions SET initial_mastered=? WHERE id=?').run(JSON.stringify([stored.term_id]),s.id);db.prepare("UPDATE progress SET status='review' WHERE term_id=?").run(stored.term_id);assert.equal(service.finish(s.id).lostMastery,1);assert.equal(service.detail(stored.term_id).times_shown,1);db.close();});
